# Generated by Django 3.2.8 on 2021-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_fio_de', models.CharField(max_length=200)),
                ('child_fio_ru', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('parent_fio_de', models.CharField(max_length=200)),
                ('parent_fio_ru', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('handy', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('is_relatives', models.BooleanField()),
                ('is_first_year', models.BooleanField()),
                ('is_3', models.BooleanField()),
                ('kontoinhaber', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('IBAN', models.CharField(max_length=200)),
                ('BIC_BLZ', models.CharField(max_length=200)),
                ('ort', models.DateTimeField()),
            ],
        ),
    ]
